#!/usr/bin/env python

from ssh_pam.core.log import Logger
from ssh_pam.core.config import Config
from ssh_pam.core import EventManager

Logger.pre_config()
Config.reload_config()
Logger.init_logging()

em = EventManager()
em.on_reload(lambda: Config.reload_config())


if __name__ == '__main__':
    from ssh_pam.server import SSHProxyServer
    server = SSHProxyServer()

    server.run()